source "https://rubygems.org"

gem "rake"
gem "rails", ">=5.2"
gem "sprockets"
gem "pg"
gem "sass-rails"
gem "uglifier"
gem "coffee-rails"
gem "jquery-rails"
gem "jbuilder"
gem "sdoc", group: :doc
gem "spring", group: :development
gem "jquery_mobile_rails"
gem "devise"
gem "thin"
gem "roo"
gem "remotipart"
gem "paperclip"
gem "paperclip_database"
gem "rubyzip"
gem "cancancan"
gem "noty-rails"
gem "eventmachine"
gem "kramdown"
gem "nokogiri"
gem "factory_bot_rails"
gem "carmen"
gem "carmen-rails"
gem "dentaku"
gem "calculus"
gem "time_difference"
gem "rmagick"
gem "htmlentities"
gem "jquery-easing-rails"
gem "magnific-popup-rails"
gem "log4r"
gem "delayed_job"
gem "delayed_job_active_record"
gem "daemons"
gem "ckeditor", "~> 4"
gem "github-markup"
gem "redcarpet"
gem "seed_dump"
gem "elasticsearch"
gem "elasticsearch-rails", "~> 5.1.0"
gem "chewy", "~> 5.2.0"
gem "curb"
gem "twilio-ruby"
gem "jsTimezoneDetect-rails"
gem "simple-rss"
gem "browser"
gem "awesome_print"
gem "open_uri_redirections"
gem "geocoder"
gem "mini_portile2"
gem "pkg-config"
gem "rest-client"
gem "immigrant"
gem "listen"
gem "rails-controller-testing"
gem "faraday_middleware"
gem "google-api-client"
gem "googlemaps-services"
# When updating rails, update the major version of composite_primary_keys: https://github.com/composite-primary-keys/composite_primary_keys
gem "composite_primary_keys", "~> 11"
gem "usda-nutrient-database"
gem "activerecord-import"
gem "reverse_markdown"
gem "posix-spawn"
gem "colorize"
gem "paypal-sdk-rest"
gem "json"
gem "active_record_query_trace"
gem "ruby-filemagic"
gem "rubocop-rspec"
gem "doorkeeper", "~> 5.4.0"
gem "devise-doorkeeper", "~> 1.1.2"
gem "doorkeeper-openid_connect", "~> 1.7.5"
gem "oauth2"
#gem "exponent-server-sdk"
gem 'exponent-server-sdk', git: "https://github.com/kevgrig/expo-server-sdk-ruby.git", branch: "issue39"
gem "sassc"
gem "bootsnap"
gem "haversine"
#gem "yelp"
