source "https://rubygems.org"

gem "rake"
gem "rails", ">=5.1.5"
# https://stackoverflow.com/a/48196438/4135310
gem "pg"
gem "sass-rails"
gem "uglifier"
gem "coffee-rails"
gem "jquery-rails"
# Older versions of turbolinks used to play nice with JQM, but recent versions didn"t and we don"t use turbolinks, so disable
#gem "turbolinks"
gem "jbuilder"
gem "sdoc", group: :doc
gem "spring", group: :development
gem "jquery_mobile_rails"
gem "devise"
gem "thin"
gem "roo"
gem "remotipart"
gem "paperclip" #, github: "thoughtbot/paperclip"
# Original gem doesn't support Rails 5
gem "paperclip_database", github: "myplaceonline/paperclip_database"
gem "rubyzip"
gem "cancancan"
gem "zeroclipboard-rails", github: "myplaceonline/zeroclipboard-rails"
gem "noty-rails"
gem "eventmachine"
gem "letter_opener", :group => :development
gem "kramdown"
gem "nokogiri"
gem "factory_bot_rails"
gem "carmen"
gem "carmen-rails"
gem "dentaku"
gem "calculus"
gem "time_difference", github: "badlamer/time_difference"
gem "yelp"
gem "rmagick"
gem "htmlentities"
gem "jquery-easing-rails"
gem "magnific-popup-rails"
gem "log4r"
gem "delayed_job", github: "collectiveidea/delayed_job"
gem "delayed_job_active_record", github: "collectiveidea/delayed_job_active_record"
gem "daemons"
gem "ckeditor", github: "galetahub/ckeditor"
#gem "ckeditor", github: "myplaceonline/ckeditor"
gem "github-markup"
gem "redcarpet"
#gem "utf8_enforcer_workaround"
gem "seed_dump"
gem "elasticsearch"
gem "elasticsearch-rails", "~> 5.1.0"
gem "chewy" #, github: "myplaceonline/chewy", branch: "v0.10.1-issue595"
gem "curb"
gem "twilio-ruby", "~> 5.2.3"
# Original gem doesn"t support Rails 5
gem "jsTimezoneDetect-rails", github: "myplaceonline/jsTimezoneDetect-rails"
gem "simple-rss"
gem "browser"
gem "awesome_print"
gem "open_uri_redirections"
gem "geocoder"
gem "mini_portile2"
gem "pkg-config"
gem "rest-client"
gem "immigrant"
gem "listen"
gem "rails-controller-testing"
gem "faraday_middleware"
gem "google-api-client"
gem "googlemaps-services"
gem "composite_primary_keys", github: "composite-primary-keys/composite_primary_keys", branch: "ar_5.1.x", ref: "3a29a1b7b02b7fef6b7f8a47f8deeb0f29d89f52"
gem "usda-nutrient-database"
gem "activerecord-import"
gem "reverse_markdown"
gem "posix-spawn"
gem "colorize"
gem "paypal-sdk-rest"
gem "json"
gem "active_record_query_trace"
gem "ruby-filemagic"
gem "rubocop-rspec"
