log4r_config:
  loggers:
    - name       : production
      level      : INFO # this should match the level in the outputter
      trace      : 'false'
      outputters :
      - datefile
    - name       : development
      level      : DEBUG
      trace      : 'true'
      outputters :
      - custom_stdout
      - debug_datefile

  outputters:
  - type: DateFileOutputter
    name: datefile
    dirname: "tmp"
    filename: "app_log4r_%u.log"
    level: INFO # this should match the level in the production logger
    formatter:
      date_pattern: '%H:%M:%S'
      pattern     : '%d %l: %m '
      type        : PatternFormatter
  - type     : StdoutOutputter
    name     : custom_stdout 
    level    : DEBUG
    formatter:
      date_pattern: '%H:%M:%S'
      pattern     : '%d %l: %m '
      type        : PatternFormatter
  - type: DateFileOutputter
    name: debug_datefile
    dirname: "tmp"
    filename: "app_log4r_debug_%u.log"
    level: DEBUG # this should match the level in the production logger
    formatter:
      date_pattern: '%H:%M:%S'
      pattern     : '%d %l: %m '
      type        : PatternFormatter
