User.current_user = User.new(
  {email: "root@myplaceonline.com", password: "password", confirmed_at: "2016-01-01 00:00:00", user_type: 1}
)
User.current_user.save!
Category.create!([
  {name: "vehicles", link: "vehicles", position: 0, parent_id: nil, additional_filtertext: "truck", icon: "famfamfam/car.png", explicit: nil, user_type_mask: nil},
  {name: "weights", link: "weights", position: 0, parent_id: 26, additional_filtertext: nil, icon: "FatCow_Icons16x16/weighing_mashine.png", explicit: nil, user_type_mask: nil},
  {name: "contacts", link: "contacts", position: 0, parent_id: nil, additional_filtertext: nil, icon: "famfamfam/user.png", explicit: nil, user_type_mask: nil},
  {name: "passports", link: "passports", position: 0, parent_id: nil, additional_filtertext: nil, icon: "FatCow_Icons16x16/change_language.png", explicit: nil, user_type_mask: nil},
  {name: "favorite_products", link: "favorite_products", position: 0, parent_id: nil, additional_filtertext: nil, icon: "FatCow_Icons16x16/star.png", explicit: nil, user_type_mask: nil},
  {name: "accomplishments", link: "accomplishments", position: 0, parent_id: nil, additional_filtertext: nil, icon: "famfamfam/award_star_gold_1.png", explicit: nil, user_type_mask: nil},
  {name: "companies", link: "companies", position: 0, parent_id: nil, additional_filtertext: nil, icon: "famfamfam/building.png", explicit: nil, user_type_mask: nil},
  {name: "calculation_forms", link: "calculation_forms", position: 0, parent_id: nil, additional_filtertext: nil, icon: "famfamfam/calculator.png", explicit: nil, user_type_mask: nil},
  {name: "calculations", link: "calculations", position: 0, parent_id: nil, additional_filtertext: nil, icon: "famfamfam/calculator_add.png", explicit: nil, user_type_mask: nil},
  {name: "credit_cards", link: "credit_cards", position: 0, parent_id: nil, additional_filtertext: nil, icon: "famfamfam/creditcards.png", explicit: nil, user_type_mask: nil},
  {name: "jokes", link: "jokes", position: 0, parent_id: nil, additional_filtertext: nil, icon: "famfamfam/emoticon_tongue.png", explicit: nil, user_type_mask: nil},
  {name: "recreational_vehicles", link: "recreational_vehicles", position: 0, parent_id: nil, additional_filtertext: "campers", icon: "famfamfam/lorry.png", explicit: nil, user_type_mask: nil},
  {name: "questions", link: "questions", position: 0, parent_id: nil, additional_filtertext: nil, icon: "famfamfam/help.png", explicit: nil, user_type_mask: nil},
  {name: "books", link: "books", position: 0, parent_id: nil, additional_filtertext: nil, icon: "FatCow_Icons16x16/book.png", explicit: nil, user_type_mask: nil},
  {name: "ideas", link: "ideas", position: 0, parent_id: nil, additional_filtertext: nil, icon: "famfamfam/lightning.png", explicit: nil, user_type_mask: nil},
  {name: "guns", link: "guns", position: 0, parent_id: nil, additional_filtertext: nil, icon: "FatCow_Icons16x16/gun.png", explicit: nil, user_type_mask: nil},
  {name: "lists", link: "lists", position: 0, parent_id: nil, additional_filtertext: nil, icon: "famfamfam/note.png", explicit: nil, user_type_mask: nil},
  {name: "sleep_measurements", link: "sleep_measurements", position: 0, parent_id: 26, additional_filtertext: nil, icon: "famfamfam/status_away.png", explicit: nil, user_type_mask: nil},
  {name: "health_insurances", link: "health_insurances", position: 0, parent_id: 26, additional_filtertext: nil, icon: "FatCow_Icons16x16/support.png", explicit: nil, user_type_mask: nil},
  {name: "movies", link: "movies", position: 0, parent_id: nil, additional_filtertext: nil, icon: "famfamfam/film.png", explicit: nil, user_type_mask: nil},
  {name: "apartments", link: "apartments", position: 0, parent_id: nil, additional_filtertext: nil, icon: "famfamfam/house.png", explicit: nil, user_type_mask: nil},
  {name: "feeds", link: "feeds", position: 0, parent_id: nil, additional_filtertext: "rss atom", icon: "famfamfam/feed.png", explicit: nil, user_type_mask: nil},
  {name: "promises", link: "promises", position: 0, parent_id: nil, additional_filtertext: nil, icon: "famfamfam/asterisk_orange.png", explicit: nil, user_type_mask: nil},
  {name: "life_goals", link: "life_goals", position: 0, parent_id: nil, additional_filtertext: "intentions do desire", icon: "FatCow_Icons16x16/compass.png", explicit: nil, user_type_mask: nil},
  {name: "acne_measurements", link: "acne_measurements", position: 0, parent_id: 26, additional_filtertext: nil, icon: "FatCow_Icons16x16/bubblechart_red.png", explicit: nil, user_type_mask: nil},
  {name: "activities", link: "activities", position: 0, parent_id: nil, additional_filtertext: nil, icon: "FatCow_Icons16x16/direction.png", explicit: nil, user_type_mask: nil},
  {name: "bank_accounts", link: "bank_accounts", position: 0, parent_id: nil, additional_filtertext: nil, icon: "FatCow_Icons16x16/bank.png", explicit: nil, user_type_mask: nil},
  {name: "blood_pressures", link: "blood_pressures", position: 0, parent_id: 26, additional_filtertext: nil, icon: "FatCow_Icons16x16/celsius.png", explicit: nil, user_type_mask: nil},
  {name: "health", link: "health", position: 0, parent_id: nil, additional_filtertext: nil, icon: "FatCow_Icons16x16/health.png", explicit: nil, user_type_mask: nil},
  {name: "heart_rates", link: "heart_rates", position: 0, parent_id: 26, additional_filtertext: nil, icon: "FatCow_Icons16x16/heart.png", explicit: nil, user_type_mask: nil},
  {name: "medicine_usages", link: "medicine_usages", position: 0, parent_id: 26, additional_filtertext: nil, icon: "FatCow_Icons16x16/injection.png", explicit: nil, user_type_mask: nil},
  {name: "meals", link: "meals", position: 0, parent_id: 26, additional_filtertext: nil, icon: "FatCow_Icons16x16/omelet.png", explicit: nil, user_type_mask: nil},
  {name: "websites", link: "websites", position: 0, parent_id: nil, additional_filtertext: nil, icon: "FatCow_Icons16x16/page_world.png", explicit: nil, user_type_mask: nil},
  {name: "heights", link: "heights", position: 0, parent_id: 26, additional_filtertext: nil, icon: "FatCow_Icons16x16/ruler.png", explicit: nil, user_type_mask: nil},
  {name: "exercises", link: "exercises", position: 0, parent_id: 26, additional_filtertext: nil, icon: "FatCow_Icons16x16/shoe.png", explicit: nil, user_type_mask: nil},
  {name: "credit_scores", link: "credit_scores", position: 0, parent_id: nil, additional_filtertext: nil, icon: "FatCow_Icons16x16/table_money.png", explicit: nil, user_type_mask: nil},
  {name: "sun_exposures", link: "sun_exposures", position: 0, parent_id: 26, additional_filtertext: nil, icon: "FatCow_Icons16x16/weather_sun.png", explicit: nil, user_type_mask: nil},
  {name: "wisdoms", link: "wisdoms", position: 0, parent_id: nil, additional_filtertext: nil, icon: "FatCow_Icons16x16/brain.png", explicit: nil, user_type_mask: nil},
  {name: "recipes", link: "recipes", position: 0, parent_id: nil, additional_filtertext: nil, icon: "FatCow_Icons16x16/chefs_hat.png", explicit: nil, user_type_mask: nil},
  {name: "pains", link: "pains", position: 0, parent_id: 26, additional_filtertext: nil, icon: "FatCow_Icons16x16/fire.png", explicit: nil, user_type_mask: nil},
  {name: "songs", link: "songs", position: 0, parent_id: nil, additional_filtertext: nil, icon: "FatCow_Icons16x16/music.png", explicit: nil, user_type_mask: nil},
  {name: "blood_tests", link: "blood_tests", position: 0, parent_id: 26, additional_filtertext: nil, icon: "FatCow_Icons16x16/injection_red.png", explicit: nil, user_type_mask: nil},
  {name: "checklists", link: "checklists", position: 0, parent_id: nil, additional_filtertext: nil, icon: "FatCow_Icons16x16/check_boxes.png", explicit: nil, user_type_mask: nil},
  {name: "medical_conditions", link: "medical_conditions", position: 0, parent_id: 26, additional_filtertext: nil, icon: "FatCow_Icons16x16/medical_record.png", explicit: nil, user_type_mask: nil},
  {name: "temperatures", link: "temperatures", position: 0, parent_id: 26, additional_filtertext: nil, icon: "FatCow_Icons16x16/temperature_warm.png", explicit: nil, user_type_mask: nil},
  {name: "headaches", link: "headaches", position: 0, parent_id: 26, additional_filtertext: nil, icon: "FatCow_Icons16x16/emotion_fire.png", explicit: nil, user_type_mask: nil},
  {name: "skin_treatments", link: "skin_treatments", position: 0, parent_id: 26, additional_filtertext: nil, icon: "FatCow_Icons16x16/user_nude.png", explicit: nil, user_type_mask: nil},
  {name: "finance", link: "finance", position: 0, parent_id: nil, additional_filtertext: nil, icon: "FatCow_Icons16x16/coins.png", explicit: nil, user_type_mask: nil},
  {name: "jobs", link: "jobs", position: 0, parent_id: nil, additional_filtertext: nil, icon: "FatCow_Icons16x16/reseller_account.png", explicit: nil, user_type_mask: nil},
  {name: "trips", link: "trips", position: 0, parent_id: nil, additional_filtertext: nil, icon: "FatCow_Icons16x16/location_pin.png", explicit: nil, user_type_mask: nil},
  {name: "periodic_payments", link: "periodic_payments", position: 0, parent_id: 48, additional_filtertext: "recurring", icon: "FatCow_Icons16x16/table_money.png", explicit: nil, user_type_mask: nil},
  {name: "to_dos", link: "to_dos", position: 0, parent_id: nil, additional_filtertext: "to dos", icon: "famfamfam/calendar.png", explicit: nil, user_type_mask: nil},
  {name: "reward_programs", link: "reward_programs", position: 0, parent_id: 48, additional_filtertext: "loyalty", icon: "FatCow_Icons16x16/teddy_bear.png", explicit: nil, user_type_mask: nil},
  {name: "computers", link: "computers", position: 0, parent_id: nil, additional_filtertext: "laptops", icon: "FatCow_Icons16x16/laptop.png", explicit: nil, user_type_mask: nil},
  {name: "life_insurances", link: "life_insurances", position: 0, parent_id: 48, additional_filtertext: nil, icon: "FatCow_Icons16x16/skull_old.png", explicit: nil, user_type_mask: nil},
  {name: "diary_entries", link: "diary_entries", position: 0, parent_id: nil, additional_filtertext: nil, icon: "FatCow_Icons16x16/report.png", explicit: nil, user_type_mask: nil},
  {name: "camp_locations", link: "camp_locations", position: 0, parent_id: nil, additional_filtertext: nil, icon: "FatCow_Icons16x16/tree.png", explicit: nil, user_type_mask: nil},
  {name: "desired_products", link: "desired_products", position: 0, parent_id: nil, additional_filtertext: "buy purchase things", icon: "FatCow_Icons16x16/cart.png", explicit: nil, user_type_mask: nil},
  {name: "locations", link: "locations", position: 0, parent_id: nil, additional_filtertext: "addresses", icon: "famfamfam/map.png", explicit: nil, user_type_mask: nil},
  {name: "passwords", link: "passwords", position: 0, parent_id: nil, additional_filtertext: "websites", icon: "famfamfam/textfield_key.png", explicit: nil, user_type_mask: nil},
  {name: "therapists", link: "therapists", position: 0, parent_id: nil, additional_filtertext: nil, icon: "FatCow_Icons16x16/account_functions.png", explicit: nil, user_type_mask: nil},
  {name: "memberships", link: "memberships", position: 0, parent_id: nil, additional_filtertext: "subscriptions", icon: "FatCow_Icons16x16/protect_share_workbook.png", explicit: nil, user_type_mask: nil},
  {name: "random", link: "random", position: 0, parent_id: nil, additional_filtertext: nil, icon: "FatCow_Icons16x16/dice.png", explicit: nil, user_type_mask: nil},
  {name: "restaurants", link: "restaurants", position: 0, parent_id: nil, additional_filtertext: "bars", icon: "FatCow_Icons16x16/cutleries.png", explicit: nil, user_type_mask: nil},
  {name: "doctors", link: "doctors", position: 0, parent_id: 26, additional_filtertext: "dentists", icon: "FatCow_Icons16x16/user_medical.png", explicit: nil, user_type_mask: nil},
  {name: "files", link: "files", position: 0, parent_id: nil, additional_filtertext: "pictures", icon: "famfamfam/attach.png", explicit: nil, user_type_mask: nil},
  {name: "dental_insurances", link: "dental_insurances", position: 0, parent_id: 26, additional_filtertext: nil, icon: "FatCow_Icons16x16/tooth.png", explicit: nil, user_type_mask: nil},
  {name: "hobbies", link: "hobbies", position: 0, parent_id: nil, additional_filtertext: nil, icon: "FatCow_Icons16x16/paper_airplane.png", explicit: nil, user_type_mask: nil},
  {name: "poems", link: "poems", position: 0, parent_id: nil, additional_filtertext: nil, icon: "FatCow_Icons16x16/quill.png", explicit: nil, user_type_mask: nil},
  {name: "musical_groups", link: "musical_groups", position: 0, parent_id: nil, additional_filtertext: "musicians artists singers", icon: "FatCow_Icons16x16/theater.png", explicit: nil, user_type_mask: nil},
  {name: "dentist_visits", link: "dentist_visits", position: 0, parent_id: 26, additional_filtertext: nil, icon: "FatCow_Icons16x16/tooth.png", explicit: nil, user_type_mask: nil},
  {name: "users", link: "users", position: 0, parent_id: nil, additional_filtertext: nil, icon: "famfamfam/group.png", explicit: nil, user_type_mask: nil},
  {name: "doctor_visits", link: "doctor_visits", position: 0, parent_id: 26, additional_filtertext: nil, icon: "FatCow_Icons16x16/bandaid.png", explicit: nil, user_type_mask: nil},
  {name: "statuses", link: "statuses", position: 0, parent_id: nil, additional_filtertext: nil, icon: "FatCow_Icons16x16/emotion_draw.png", explicit: nil, user_type_mask: nil},
  {name: "notepads", link: "notepads", position: 0, parent_id: nil, additional_filtertext: nil, icon: "FatCow_Icons16x16/note.png", explicit: nil, user_type_mask: nil},
  {name: "concerts", link: "concerts", position: 0, parent_id: nil, additional_filtertext: nil, icon: "FatCow_Icons16x16/speakers.png", explicit: nil, user_type_mask: nil},
  {name: "shopping_lists", link: "shopping_lists", position: 0, parent_id: nil, additional_filtertext: nil, icon: "FatCow_Icons16x16/cart_put.png", explicit: nil, user_type_mask: nil},
  {name: "tools", link: "tools", position: 0, parent_id: nil, additional_filtertext: nil, icon: "famfamfam/wrench.png", explicit: nil, user_type_mask: nil},
  {name: "groups", link: "groups", position: 0, parent_id: nil, additional_filtertext: nil, icon: "FatCow_Icons16x16/group.png", explicit: nil, user_type_mask: nil},
  {name: "phones", link: "phones", position: 0, parent_id: nil, additional_filtertext: nil, icon: "FatCow_Icons16x16/phone.png", explicit: nil, user_type_mask: nil},
  {name: "promotions", link: "promotions", position: 0, parent_id: 48, additional_filtertext: "coupons gifts vouchers credits", icon: "FatCow_Icons16x16/coins_in_hand.png", explicit: nil, user_type_mask: nil},
  {name: "movie_theaters", link: "movie_theaters", position: 0, parent_id: nil, additional_filtertext: nil, icon: "FatCow_Icons16x16/movies.png", explicit: nil, user_type_mask: nil},
  {name: "gas_stations", link: "gas_stations", position: 0, parent_id: nil, additional_filtertext: "propane diesel fillup", icon: "FatCow_Icons16x16/gas.png", explicit: nil, user_type_mask: nil},
  {name: "events", link: "events", position: 0, parent_id: nil, additional_filtertext: nil, icon: "FatCow_Icons16x16/calendar_view_day.png", explicit: nil, user_type_mask: nil},
  {name: "stocks", link: "stocks", position: 0, parent_id: 48, additional_filtertext: nil, icon: "FatCow_Icons16x16/finance.png", explicit: nil, user_type_mask: nil},
  {name: "museums", link: "museums", position: 0, parent_id: nil, additional_filtertext: nil, icon: "FatCow_Icons16x16/cup_gold.png", explicit: nil, user_type_mask: nil},
  {name: "playlists", link: "playlists", position: 0, parent_id: nil, additional_filtertext: nil, icon: "FatCow_Icons16x16/ear_listen.png", explicit: nil, user_type_mask: nil},
  {name: "bars", link: "bars", position: 0, parent_id: nil, additional_filtertext: "restaurants", icon: "FatCow_Icons16x16/glass_of_wine_full.png", explicit: nil, user_type_mask: nil},
  {name: "treks", link: "treks", position: 0, parent_id: nil, additional_filtertext: "hikes", icon: "FatCow_Icons16x16/tree.png", explicit: nil, user_type_mask: nil},
  {name: "date_locations", link: "date_locations", position: 0, parent_id: nil, additional_filtertext: "dates", icon: "FatCow_Icons16x16/heart.png", explicit: nil, user_type_mask: nil},
  {name: "money_balances", link: "money_balances", position: 0, parent_id: 48, additional_filtertext: "lend owe rent", icon: "FatCow_Icons16x16/blackboard_sum.png", explicit: nil, user_type_mask: nil},
  {name: "permissions", link: "permissions", position: 0, parent_id: nil, additional_filtertext: "share", icon: "FatCow_Icons16x16/lock.png", explicit: nil, user_type_mask: nil}
])
