class ChangeIdentityColumns < ActiveRecord::Migration
  def change
    rename_column :accomplishments, :identity_id, :owner_id
    rename_column :acne_measurements, :identity_id, :owner_id
    rename_column :acne_measurement_pictures, :identity_id, :owner_id
    rename_column :activities, :identity_id, :owner_id
    rename_column :apartment_leases, :identity_id, :owner_id
    rename_column :apartments, :identity_id, :owner_id
    rename_column :bank_accounts, :identity_id, :owner_id
    rename_column :blood_concentrations, :identity_id, :owner_id
    rename_column :blood_pressures, :identity_id, :owner_id
    rename_column :blood_test_results, :identity_id, :owner_id
    rename_column :blood_tests, :identity_id, :owner_id
    rename_column :calculation_elements, :identity_id, :owner_id
    rename_column :calculation_forms, :identity_id, :owner_id
    rename_column :calculation_inputs, :identity_id, :owner_id
    rename_column :calculation_operands, :identity_id, :owner_id
    rename_column :calculations, :identity_id, :owner_id
    rename_column :camp_locations, :identity_id, :owner_id
    rename_column :cashbacks, :identity_id, :owner_id
    rename_column :category_points_amounts, :identity_id, :owner_id
    rename_column :checklist_items, :identity_id, :owner_id
    rename_column :checklist_references, :identity_id, :owner_id
    rename_column :checklists, :identity_id, :owner_id
    rename_column :companies, :identity_id, :owner_id
    rename_column :computers, :identity_id, :owner_id
    rename_column :contacts, :identity_id, :owner_id
    rename_column :conversations, :identity_id, :owner_id
    rename_column :credit_card_cashbacks, :identity_id, :owner_id
    rename_column :credit_cards, :identity_id, :owner_id
    rename_column :credit_scores, :identity_id, :owner_id
    rename_column :desired_products, :identity_id, :owner_id
    rename_column :diary_entries, :identity_id, :owner_id
    rename_column :drinks, :identity_id, :owner_id
    rename_column :exercises, :identity_id, :owner_id
    rename_column :feeds, :identity_id, :owner_id
    rename_column :food_ingredients, :identity_id, :owner_id
    rename_column :foods, :identity_id, :owner_id
    rename_column :guns, :identity_id, :owner_id
    rename_column :headaches, :identity_id, :owner_id
    rename_column :heart_rates, :identity_id, :owner_id
    rename_column :heights, :identity_id, :owner_id
    rename_column :hypotheses, :identity_id, :owner_id
    rename_column :hypothesis_experiments, :identity_id, :owner_id
    rename_column :ideas, :identity_id, :owner_id
    rename_column :identity_drivers_licenses, :identity_id, :owner_id
    rename_column :identity_emails, :identity_id, :owner_id
    rename_column :identity_file_folders, :identity_id, :owner_id
    rename_column :identity_files, :identity_id, :owner_id
    rename_column :identity_locations, :identity_id, :owner_id
    rename_column :identity_phones, :identity_id, :owner_id
    rename_column :identity_pictures, :identity_id, :owner_id
    rename_column :identity_relationships, :identity_id, :owner_id
    rename_column :job_salaries, :identity_id, :owner_id
    rename_column :jobs, :identity_id, :owner_id
    rename_column :jokes, :identity_id, :owner_id
    rename_column :life_goals, :identity_id, :owner_id
    rename_column :life_insurances, :identity_id, :owner_id
    rename_column :list_items, :identity_id, :owner_id
    rename_column :lists, :identity_id, :owner_id
    rename_column :loans, :identity_id, :owner_id
    rename_column :location_phones, :identity_id, :owner_id
    rename_column :locations, :identity_id, :owner_id
    rename_column :meal_drinks, :identity_id, :owner_id
    rename_column :meal_foods, :identity_id, :owner_id
    rename_column :meal_vitamins, :identity_id, :owner_id
    rename_column :meals, :identity_id, :owner_id
    rename_column :medical_condition_instances, :identity_id, :owner_id
    rename_column :medical_conditions, :identity_id, :owner_id
    rename_column :medicine_usage_medicines, :identity_id, :owner_id
    rename_column :medicine_usages, :identity_id, :owner_id
    rename_column :medicines, :identity_id, :owner_id
    rename_column :movies, :identity_id, :owner_id
    rename_column :pains, :identity_id, :owner_id
    rename_column :passport_pictures, :identity_id, :owner_id
    rename_column :passports, :identity_id, :owner_id
    rename_column :password_secrets, :identity_id, :owner_id
    rename_column :passwords, :identity_id, :owner_id
    rename_column :periodic_payments, :identity_id, :owner_id
    rename_column :promises, :identity_id, :owner_id
    rename_column :promotions, :identity_id, :owner_id
    rename_column :questions, :identity_id, :owner_id
    rename_column :recipes, :identity_id, :owner_id
    rename_column :recreational_vehicle_insurances, :identity_id, :owner_id
    rename_column :recreational_vehicle_loans, :identity_id, :owner_id
    rename_column :recreational_vehicle_pictures, :identity_id, :owner_id
    rename_column :recreational_vehicles, :identity_id, :owner_id
    rename_column :restaurants, :identity_id, :owner_id
    rename_column :reward_programs, :identity_id, :owner_id
    rename_column :skin_treatments, :identity_id, :owner_id
    rename_column :sleep_measurements, :identity_id, :owner_id
    rename_column :songs, :identity_id, :owner_id
    rename_column :subscriptions, :identity_id, :owner_id
    rename_column :sun_exposures, :identity_id, :owner_id
    rename_column :temperatures, :identity_id, :owner_id
    rename_column :to_dos, :identity_id, :owner_id
    rename_column :trip_pictures, :identity_id, :owner_id
    rename_column :trips, :identity_id, :owner_id
    rename_column :vehicle_insurances, :identity_id, :owner_id
    rename_column :vehicle_loans, :identity_id, :owner_id
    rename_column :vehicle_pictures, :identity_id, :owner_id
    rename_column :vehicle_services, :identity_id, :owner_id
    rename_column :vehicles, :identity_id, :owner_id
    rename_column :vitamin_ingredients, :identity_id, :owner_id
    rename_column :vitamins, :identity_id, :owner_id
    rename_column :websites, :identity_id, :owner_id
    rename_column :weights, :identity_id, :owner_id
    rename_column :wisdoms, :identity_id, :owner_id
  end
end
