class AddKeys < ActiveRecord::Migration
  def change
    IdentityLocation.find(8).delete
    TripPicture.find(732).delete
    add_foreign_key "accomplishments", "identities", name: "accomplishments_identity_id_fk"
    add_foreign_key "acne_measurement_pictures", "acne_measurements", name: "acne_measurement_pictures_acne_measurement_id_fk"
    add_foreign_key "acne_measurement_pictures", "identity_files", name: "acne_measurement_pictures_identity_file_id_fk"
    add_foreign_key "acne_measurement_pictures", "identities", name: "acne_measurement_pictures_identity_id_fk"
    add_foreign_key "acne_measurements", "identities", name: "acne_measurements_identity_id_fk"
    add_foreign_key "activities", "identities", name: "activities_identity_id_fk"
    add_foreign_key "apartment_leases", "apartments", name: "apartment_leases_apartment_id_fk"
    add_foreign_key "apartment_leases", "identities", name: "apartment_leases_identity_id_fk"
    add_foreign_key "apartment_pictures", "apartments", name: "apartment_pictures_apartment_id_fk"
    add_foreign_key "apartment_pictures", "identity_files", name: "apartment_pictures_identity_file_id_fk"
    add_foreign_key "apartment_pictures", "identities", name: "apartment_pictures_identity_id_fk"
    add_foreign_key "apartment_trash_pickups", "apartments", name: "apartment_trash_pickups_apartment_id_fk"
    add_foreign_key "apartment_trash_pickups", "identities", name: "apartment_trash_pickups_identity_id_fk"
    add_foreign_key "apartment_trash_pickups", "repeats", name: "apartment_trash_pickups_repeat_id_fk"
    add_foreign_key "apartments", "identities", name: "apartments_identity_id_fk"
    add_foreign_key "apartments", "contacts", column: "landlord_id", name: "apartments_landlord_id_fk"
    add_foreign_key "apartments", "locations", name: "apartments_location_id_fk"
    add_foreign_key "bank_accounts", "encrypted_values", column: "account_number_encrypted_id", name: "bank_accounts_account_number_encrypted_id_fk"
    add_foreign_key "bank_accounts", "companies", name: "bank_accounts_company_id_fk"
    add_foreign_key "bank_accounts", "locations", column: "home_address_id", name: "bank_accounts_home_address_id_fk"
    add_foreign_key "bank_accounts", "identities", name: "bank_accounts_identity_id_fk"
    add_foreign_key "bank_accounts", "passwords", name: "bank_accounts_password_id_fk"
    add_foreign_key "bank_accounts", "encrypted_values", column: "pin_encrypted_id", name: "bank_accounts_pin_encrypted_id_fk"
    add_foreign_key "bank_accounts", "encrypted_values", column: "routing_number_encrypted_id", name: "bank_accounts_routing_number_encrypted_id_fk"
    add_foreign_key "blood_concentrations", "identities", name: "blood_concentrations_identity_id_fk"
    add_foreign_key "blood_pressures", "identities", name: "blood_pressures_identity_id_fk"
    add_foreign_key "blood_test_results", "blood_concentrations", name: "blood_test_results_blood_concentration_id_fk"
    add_foreign_key "blood_test_results", "blood_tests", name: "blood_test_results_blood_test_id_fk"
    add_foreign_key "blood_test_results", "identities", name: "blood_test_results_identity_id_fk"
    add_foreign_key "blood_tests", "identities", name: "blood_tests_identity_id_fk"
    add_foreign_key "books", "identities", name: "books_identity_id_fk"
    add_foreign_key "books", "contacts", column: "recommender_id", name: "books_recommender_id_fk"
    add_foreign_key "calculation_elements", "identities", name: "calculation_elements_identity_id_fk"
    add_foreign_key "calculation_elements", "calculation_operands", column: "left_operand_id", name: "calculation_elements_left_operand_id_fk"
    add_foreign_key "calculation_elements", "calculation_operands", column: "right_operand_id", name: "calculation_elements_right_operand_id_fk"
    add_foreign_key "calculation_forms", "identities", name: "calculation_forms_identity_id_fk"
    add_foreign_key "calculation_forms", "calculation_elements", column: "root_element_id", name: "calculation_forms_root_element_id_fk"
    add_foreign_key "calculation_inputs", "calculation_forms", name: "calculation_inputs_calculation_form_id_fk"
    add_foreign_key "calculation_inputs", "identities", name: "calculation_inputs_identity_id_fk"
    add_foreign_key "calculation_operands", "calculation_elements", name: "calculation_operands_calculation_element_id_fk"
    add_foreign_key "calculation_operands", "calculation_inputs", name: "calculation_operands_calculation_input_id_fk"
    add_foreign_key "calculation_operands", "identities", name: "calculation_operands_identity_id_fk"
    add_foreign_key "calculations", "calculation_forms", name: "calculations_calculation_form_id_fk"
    add_foreign_key "calculations", "identities", name: "calculations_identity_id_fk"
    add_foreign_key "calculations", "calculation_forms", column: "original_calculation_form_id", name: "calculations_original_calculation_form_id_fk"
    add_foreign_key "calendars", "identities", name: "calendars_identity_id_fk"
    add_foreign_key "camp_locations", "identities", name: "camp_locations_identity_id_fk"
    add_foreign_key "camp_locations", "locations", name: "camp_locations_location_id_fk"
    add_foreign_key "camp_locations", "memberships", name: "camp_locations_membership_id_fk"
    add_foreign_key "cashbacks", "identities", name: "cashbacks_identity_id_fk"
    add_foreign_key "categories", "categories", column: "parent_id", name: "categories_parent_id_fk"
    add_foreign_key "category_points_amounts", "categories", name: "category_points_amounts_category_id_fk"
    add_foreign_key "category_points_amounts", "identities", name: "category_points_amounts_identity_id_fk"
    add_foreign_key "checklist_items", "checklists", name: "checklist_items_checklist_id_fk"
    add_foreign_key "checklist_items", "identities", name: "checklist_items_identity_id_fk"
    add_foreign_key "checklist_references", "checklists", name: "checklist_references_checklist_id_fk"
    add_foreign_key "checklist_references", "checklists", column: "checklist_parent_id", name: "checklist_references_checklist_parent_id_fk"
    add_foreign_key "checklist_references", "identities", name: "checklist_references_identity_id_fk"
    add_foreign_key "checklists", "identities", name: "checklists_identity_id_fk"
    add_foreign_key "companies", "identities", name: "companies_identity_id_fk"
    add_foreign_key "companies", "locations", name: "companies_location_id_fk"
    add_foreign_key "complete_due_items", "calendars", name: "complete_due_items_calendar_id_fk"
    add_foreign_key "complete_due_items", "identities", name: "complete_due_items_identity_id_fk"
    add_foreign_key "computers", "passwords", column: "administrator_id", name: "computers_administrator_id_fk"
    add_foreign_key "computers", "identities", name: "computers_identity_id_fk"
    add_foreign_key "computers", "passwords", column: "main_user_id", name: "computers_main_user_id_fk"
    add_foreign_key "computers", "companies", column: "manufacturer_id", name: "computers_manufacturer_id_fk"
    add_foreign_key "concert_musical_groups", "concerts", name: "concert_musical_groups_concert_id_fk"
    add_foreign_key "concert_musical_groups", "identities", name: "concert_musical_groups_identity_id_fk"
    add_foreign_key "concert_musical_groups", "musical_groups", name: "concert_musical_groups_musical_group_id_fk"
    add_foreign_key "concerts", "identities", name: "concerts_identity_id_fk"
    add_foreign_key "concerts", "locations", name: "concerts_location_id_fk"
    add_foreign_key "contacts", "identities", column: "contact_identity_id", name: "contacts_contact_identity_id_fk"
    add_foreign_key "contacts", "identities", name: "contacts_identity_id_fk"
    add_foreign_key "conversations", "contacts", name: "conversations_contact_id_fk"
    add_foreign_key "conversations", "identities", name: "conversations_identity_id_fk"
    add_foreign_key "credit_card_cashbacks", "cashbacks", name: "credit_card_cashbacks_cashback_id_fk"
    add_foreign_key "credit_card_cashbacks", "credit_cards", name: "credit_card_cashbacks_credit_card_id_fk"
    add_foreign_key "credit_card_cashbacks", "identities", name: "credit_card_cashbacks_identity_id_fk"
    add_foreign_key "credit_cards", "locations", column: "address_id", name: "credit_cards_address_id_fk"
    add_foreign_key "credit_cards", "encrypted_values", column: "expires_encrypted_id", name: "credit_cards_expires_encrypted_id_fk"
    add_foreign_key "credit_cards", "identities", name: "credit_cards_identity_id_fk"
    add_foreign_key "credit_cards", "encrypted_values", column: "number_encrypted_id", name: "credit_cards_number_encrypted_id_fk"
    add_foreign_key "credit_cards", "passwords", name: "credit_cards_password_id_fk"
    add_foreign_key "credit_cards", "encrypted_values", column: "pin_encrypted_id", name: "credit_cards_pin_encrypted_id_fk"
    add_foreign_key "credit_cards", "encrypted_values", column: "security_code_encrypted_id", name: "credit_cards_security_code_encrypted_id_fk"
    add_foreign_key "credit_scores", "identities", name: "credit_scores_identity_id_fk"
    add_foreign_key "date_locations", "identities", name: "date_locations_identity_id_fk"
    add_foreign_key "date_locations", "locations", name: "date_locations_location_id_fk"
    add_foreign_key "dental_insurances", "doctors", name: "dental_insurances_doctor_id_fk"
    add_foreign_key "dental_insurances", "companies", column: "group_company_id", name: "dental_insurances_group_company_id_fk"
    add_foreign_key "dental_insurances", "identities", name: "dental_insurances_identity_id_fk"
    add_foreign_key "dental_insurances", "companies", column: "insurance_company_id", name: "dental_insurances_insurance_company_id_fk"
    add_foreign_key "dental_insurances", "passwords", name: "dental_insurances_password_id_fk"
    add_foreign_key "dental_insurances", "periodic_payments", name: "dental_insurances_periodic_payment_id_fk"
    add_foreign_key "dentist_visits", "dental_insurances", name: "dentist_visits_dental_insurance_id_fk"
    add_foreign_key "dentist_visits", "doctors", column: "dentist_id", name: "dentist_visits_dentist_id_fk"
    add_foreign_key "dentist_visits", "identities", name: "dentist_visits_identity_id_fk"
    add_foreign_key "desired_products", "identities", name: "desired_products_identity_id_fk"
    add_foreign_key "diary_entries", "identities", name: "diary_entries_identity_id_fk"
    add_foreign_key "doctor_visits", "doctors", name: "doctor_visits_doctor_id_fk"
    add_foreign_key "doctor_visits", "health_insurances", name: "doctor_visits_health_insurance_id_fk"
    add_foreign_key "doctor_visits", "identities", name: "doctor_visits_identity_id_fk"
    add_foreign_key "doctors", "contacts", name: "doctors_contact_id_fk"
    add_foreign_key "doctors", "identities", name: "doctors_identity_id_fk"
    add_foreign_key "drinks", "identities", name: "drinks_identity_id_fk"
    add_foreign_key "due_items", "calendars", name: "due_items_calendar_id_fk"
    add_foreign_key "due_items", "identities", name: "due_items_identity_id_fk"
    add_foreign_key "encrypted_values", "users", name: "encrypted_values_user_id_fk"
    add_foreign_key "events", "identities", name: "events_identity_id_fk"
    add_foreign_key "events", "locations", name: "events_location_id_fk"
    add_foreign_key "events", "repeats", name: "events_repeat_id_fk"
    add_foreign_key "exercises", "identities", name: "exercises_identity_id_fk"
    add_foreign_key "favorite_products", "identities", name: "favorite_products_identity_id_fk"
    add_foreign_key "feeds", "identities", name: "feeds_identity_id_fk"
    add_foreign_key "food_ingredients", "foods", name: "food_ingredients_food_id_fk"
    add_foreign_key "food_ingredients", "identities", name: "food_ingredients_identity_id_fk"
    add_foreign_key "food_ingredients", "foods", column: "parent_food_id", name: "food_ingredients_parent_food_id_fk"
    add_foreign_key "foods", "identities", name: "foods_identity_id_fk"
    add_foreign_key "gas_stations", "identities", name: "gas_stations_identity_id_fk"
    add_foreign_key "gas_stations", "locations", name: "gas_stations_location_id_fk"
    add_foreign_key "group_contacts", "contacts", name: "group_contacts_contact_id_fk"
    add_foreign_key "group_contacts", "groups", name: "group_contacts_group_id_fk"
    add_foreign_key "group_contacts", "identities", name: "group_contacts_identity_id_fk"
    add_foreign_key "groups", "identities", name: "groups_identity_id_fk"
    add_foreign_key "gun_registrations", "guns", name: "gun_registrations_gun_id_fk"
    add_foreign_key "gun_registrations", "identities", name: "gun_registrations_identity_id_fk"
    add_foreign_key "gun_registrations", "locations", name: "gun_registrations_location_id_fk"
    add_foreign_key "guns", "identities", name: "guns_identity_id_fk"
    add_foreign_key "headaches", "identities", name: "headaches_identity_id_fk"
    add_foreign_key "health_insurances", "doctors", name: "health_insurances_doctor_id_fk"
    add_foreign_key "health_insurances", "companies", column: "group_company_id", name: "health_insurances_group_company_id_fk"
    add_foreign_key "health_insurances", "identities", name: "health_insurances_identity_id_fk"
    add_foreign_key "health_insurances", "companies", column: "insurance_company_id", name: "health_insurances_insurance_company_id_fk"
    add_foreign_key "health_insurances", "passwords", name: "health_insurances_password_id_fk"
    add_foreign_key "health_insurances", "periodic_payments", name: "health_insurances_periodic_payment_id_fk"
    add_foreign_key "heart_rates", "identities", name: "heart_rates_identity_id_fk"
    add_foreign_key "heights", "identities", name: "heights_identity_id_fk"
    add_foreign_key "hobbies", "identities", name: "hobbies_identity_id_fk"
    add_foreign_key "hypotheses", "identities", name: "hypotheses_identity_id_fk"
    add_foreign_key "hypotheses", "questions", name: "hypotheses_question_id_fk"
    add_foreign_key "hypothesis_experiments", "hypotheses", name: "hypothesis_experiments_hypothesis_id_fk"
    add_foreign_key "hypothesis_experiments", "identities", name: "hypothesis_experiments_identity_id_fk"
    add_foreign_key "ideas", "identities", name: "ideas_identity_id_fk"
    add_foreign_key "identities", "users", name: "identities_user_id_fk"
    add_foreign_key "identity_drivers_licenses", "identity_files", name: "identity_drivers_licenses_identity_file_id_fk"
    add_foreign_key "identity_drivers_licenses", "identities", name: "identity_drivers_licenses_identity_id_fk"
    add_foreign_key "identity_drivers_licenses", "identities", column: "parent_identity_id", name: "identity_drivers_licenses_parent_identity_id_fk"
    add_foreign_key "identity_emails", "identities", name: "identity_emails_identity_id_fk"
    add_foreign_key "identity_emails", "identities", column: "parent_identity_id", name: "identity_emails_parent_identity_id_fk"
    add_foreign_key "identity_file_folders", "identities", name: "identity_file_folders_identity_id_fk"
    add_foreign_key "identity_file_folders", "identity_file_folders", column: "parent_folder_id", name: "identity_file_folders_parent_folder_id_fk"
    add_foreign_key "identity_files", "encrypted_values", column: "encrypted_password_id", name: "identity_files_encrypted_password_id_fk"
    add_foreign_key "identity_files", "identity_file_folders", column: "folder_id", name: "identity_files_folder_id_fk"
    add_foreign_key "identity_files", "identities", name: "identity_files_identity_id_fk"
    add_foreign_key "identity_locations", "identities", name: "identity_locations_identity_id_fk"
    add_foreign_key "identity_locations", "locations", name: "identity_locations_location_id_fk"
    add_foreign_key "identity_locations", "identities", column: "parent_identity_id", name: "identity_locations_parent_identity_id_fk"
    add_foreign_key "identity_phones", "identities", name: "identity_phones_identity_id_fk"
    add_foreign_key "identity_phones", "identities", column: "parent_identity_id", name: "identity_phones_parent_identity_id_fk"
    add_foreign_key "identity_pictures", "identity_files", name: "identity_pictures_identity_file_id_fk"
    add_foreign_key "identity_pictures", "identities", name: "identity_pictures_identity_id_fk"
    add_foreign_key "identity_pictures", "identities", column: "parent_identity_id", name: "identity_pictures_parent_identity_id_fk"
    add_foreign_key "identity_relationships", "contacts", name: "identity_relationships_contact_id_fk"
    add_foreign_key "identity_relationships", "identities", name: "identity_relationships_identity_id_fk"
    add_foreign_key "identity_relationships", "identities", column: "parent_identity_id", name: "identity_relationships_parent_identity_id_fk"
    add_foreign_key "job_salaries", "identities", name: "job_salaries_identity_id_fk"
    add_foreign_key "job_salaries", "jobs", name: "job_salaries_job_id_fk"
    add_foreign_key "jobs", "companies", name: "jobs_company_id_fk"
    add_foreign_key "jobs", "identities", name: "jobs_identity_id_fk"
    add_foreign_key "jobs", "locations", column: "internal_address_id", name: "jobs_internal_address_id_fk"
    add_foreign_key "jobs", "contacts", column: "manager_contact_id", name: "jobs_manager_contact_id_fk"
    add_foreign_key "jokes", "identities", name: "jokes_identity_id_fk"
    add_foreign_key "life_goals", "identities", name: "life_goals_identity_id_fk"
    add_foreign_key "life_insurances", "companies", name: "life_insurances_company_id_fk"
    add_foreign_key "life_insurances", "identities", name: "life_insurances_identity_id_fk"
    add_foreign_key "life_insurances", "periodic_payments", name: "life_insurances_periodic_payment_id_fk"
    add_foreign_key "list_items", "identities", name: "list_items_identity_id_fk"
    add_foreign_key "list_items", "lists", name: "list_items_list_id_fk"
    add_foreign_key "lists", "identities", name: "lists_identity_id_fk"
    add_foreign_key "loans", "identities", name: "loans_identity_id_fk"
    add_foreign_key "location_phones", "identities", name: "location_phones_identity_id_fk"
    add_foreign_key "location_phones", "locations", name: "location_phones_location_id_fk"
    add_foreign_key "locations", "identities", name: "locations_identity_id_fk"
    add_foreign_key "meal_drinks", "drinks", name: "meal_drinks_drink_id_fk"
    add_foreign_key "meal_drinks", "identities", name: "meal_drinks_identity_id_fk"
    add_foreign_key "meal_drinks", "meals", name: "meal_drinks_meal_id_fk"
    add_foreign_key "meal_foods", "foods", name: "meal_foods_food_id_fk"
    add_foreign_key "meal_foods", "identities", name: "meal_foods_identity_id_fk"
    add_foreign_key "meal_foods", "meals", name: "meal_foods_meal_id_fk"
    add_foreign_key "meal_vitamins", "identities", name: "meal_vitamins_identity_id_fk"
    add_foreign_key "meal_vitamins", "meals", name: "meal_vitamins_meal_id_fk"
    add_foreign_key "meal_vitamins", "vitamins", name: "meal_vitamins_vitamin_id_fk"
    add_foreign_key "meals", "identities", name: "meals_identity_id_fk"
    add_foreign_key "meals", "locations", name: "meals_location_id_fk"
    add_foreign_key "medical_condition_instances", "identities", name: "medical_condition_instances_identity_id_fk"
    add_foreign_key "medical_condition_instances", "medical_conditions", name: "medical_condition_instances_medical_condition_id_fk"
    add_foreign_key "medical_conditions", "identities", name: "medical_conditions_identity_id_fk"
    add_foreign_key "medicine_usage_medicines", "identities", name: "medicine_usage_medicines_identity_id_fk"
    add_foreign_key "medicine_usage_medicines", "medicines", name: "medicine_usage_medicines_medicine_id_fk"
    add_foreign_key "medicine_usage_medicines", "medicine_usages", name: "medicine_usage_medicines_medicine_usage_id_fk"
    add_foreign_key "medicine_usages", "identities", name: "medicine_usages_identity_id_fk"
    add_foreign_key "medicines", "identities", name: "medicines_identity_id_fk"
    add_foreign_key "memberships", "identities", name: "memberships_identity_id_fk"
    add_foreign_key "memberships", "periodic_payments", name: "memberships_periodic_payment_id_fk"
    add_foreign_key "movie_theaters", "identities", name: "movie_theaters_identity_id_fk"
    add_foreign_key "movie_theaters", "locations", name: "movie_theaters_location_id_fk"
    add_foreign_key "movies", "identities", name: "movies_identity_id_fk"
    add_foreign_key "movies", "contacts", column: "recommender_id", name: "movies_recommender_id_fk"
    add_foreign_key "museums", "identities", name: "museums_identity_id_fk"
    add_foreign_key "museums", "locations", name: "museums_location_id_fk"
    add_foreign_key "museums", "websites", name: "museums_website_id_fk"
    add_foreign_key "musical_groups", "identities", name: "musical_groups_identity_id_fk"
    add_foreign_key "myplaceonline_quick_category_displays", "identities", name: "myplaceonline_quick_category_displays_identity_id_fk"
    add_foreign_key "myplaceonline_searches", "identities", name: "myplaceonline_searches_identity_id_fk"
    add_foreign_key "myplets", "identities", name: "myplets_identity_id_fk"
    add_foreign_key "notepads", "identities", name: "notepads_identity_id_fk"
    add_foreign_key "pains", "identities", name: "pains_identity_id_fk"
    add_foreign_key "passport_pictures", "identity_files", name: "passport_pictures_identity_file_id_fk"
    add_foreign_key "passport_pictures", "identities", name: "passport_pictures_identity_id_fk"
    add_foreign_key "passport_pictures", "passports", name: "passport_pictures_passport_id_fk"
    add_foreign_key "passports", "identities", name: "passports_identity_id_fk"
    add_foreign_key "password_secrets", "encrypted_values", column: "answer_encrypted_id", name: "password_secrets_answer_encrypted_id_fk"
    add_foreign_key "password_secrets", "identities", name: "password_secrets_identity_id_fk"
    add_foreign_key "password_secrets", "passwords", name: "password_secrets_password_id_fk"
    add_foreign_key "passwords", "identities", name: "passwords_identity_id_fk"
    add_foreign_key "passwords", "encrypted_values", column: "password_encrypted_id", name: "passwords_password_encrypted_id_fk"
    add_foreign_key "periodic_payments", "identities", name: "periodic_payments_identity_id_fk"
    add_foreign_key "phones", "identities", name: "phones_identity_id_fk"
    add_foreign_key "phones", "companies", column: "manufacturer_id", name: "phones_manufacturer_id_fk"
    add_foreign_key "phones", "passwords", name: "phones_password_id_fk"
    add_foreign_key "playlist_songs", "identities", name: "playlist_songs_identity_id_fk"
    add_foreign_key "playlist_songs", "playlists", name: "playlist_songs_playlist_id_fk"
    add_foreign_key "playlist_songs", "songs", name: "playlist_songs_song_id_fk"
    add_foreign_key "playlists", "identities", name: "playlists_identity_id_fk"
    add_foreign_key "poems", "identities", name: "poems_identity_id_fk"
    add_foreign_key "point_displays", "identities", name: "point_displays_identity_id_fk"
    add_foreign_key "promises", "identities", name: "promises_identity_id_fk"
    add_foreign_key "promotions", "identities", name: "promotions_identity_id_fk"
    add_foreign_key "questions", "identities", name: "questions_identity_id_fk"
    add_foreign_key "recipes", "identities", name: "recipes_identity_id_fk"
    add_foreign_key "recreational_vehicle_insurances", "companies", name: "recreational_vehicle_insurances_company_id_fk"
    add_foreign_key "recreational_vehicle_insurances", "identities", name: "recreational_vehicle_insurances_identity_id_fk"
    add_foreign_key "recreational_vehicle_insurances", "periodic_payments", name: "recreational_vehicle_insurances_periodic_payment_id_fk"
    add_foreign_key "recreational_vehicle_insurances", "recreational_vehicles", name: "recreational_vehicle_insurances_recreational_vehicle_id_fk"
    add_foreign_key "recreational_vehicle_loans", "identities", name: "recreational_vehicle_loans_identity_id_fk"
    add_foreign_key "recreational_vehicle_loans", "loans", name: "recreational_vehicle_loans_loan_id_fk"
    add_foreign_key "recreational_vehicle_loans", "recreational_vehicles", name: "recreational_vehicle_loans_recreational_vehicle_id_fk"
    add_foreign_key "recreational_vehicle_measurements", "identities", name: "recreational_vehicle_measurements_identity_id_fk"
    add_foreign_key "recreational_vehicle_measurements", "recreational_vehicles", name: "recreational_vehicle_measurements_recreational_vehicle_id_fk"
    add_foreign_key "recreational_vehicle_pictures", "identity_files", name: "recreational_vehicle_pictures_identity_file_id_fk"
    add_foreign_key "recreational_vehicle_pictures", "identities", name: "recreational_vehicle_pictures_identity_id_fk"
    add_foreign_key "recreational_vehicle_pictures", "recreational_vehicles", name: "recreational_vehicle_pictures_recreational_vehicle_id_fk"
    add_foreign_key "recreational_vehicles", "identities", name: "recreational_vehicles_identity_id_fk"
    add_foreign_key "recreational_vehicles", "locations", column: "location_purchased_id", name: "recreational_vehicles_location_purchased_id_fk"
    add_foreign_key "repeats", "identities", name: "repeats_identity_id_fk"
    add_foreign_key "restaurants", "identities", name: "restaurants_identity_id_fk"
    add_foreign_key "restaurants", "locations", name: "restaurants_location_id_fk"
    add_foreign_key "reward_programs", "identities", name: "reward_programs_identity_id_fk"
    add_foreign_key "reward_programs", "passwords", name: "reward_programs_password_id_fk"
    add_foreign_key "shares", "identities", name: "shares_identity_id_fk"
    add_foreign_key "shopping_list_items", "identities", name: "shopping_list_items_identity_id_fk"
    add_foreign_key "shopping_list_items", "shopping_lists", name: "shopping_list_items_shopping_list_id_fk"
    add_foreign_key "shopping_lists", "identities", name: "shopping_lists_identity_id_fk"
    add_foreign_key "skin_treatments", "identities", name: "skin_treatments_identity_id_fk"
    add_foreign_key "sleep_measurements", "identities", name: "sleep_measurements_identity_id_fk"
    add_foreign_key "snoozed_due_items", "calendars", name: "snoozed_due_items_calendar_id_fk"
    add_foreign_key "snoozed_due_items", "identities", name: "snoozed_due_items_identity_id_fk"
    add_foreign_key "songs", "identity_files", name: "songs_identity_file_id_fk"
    add_foreign_key "songs", "identities", name: "songs_identity_id_fk"
    add_foreign_key "songs", "musical_groups", name: "songs_musical_group_id_fk"
    add_foreign_key "statuses", "identities", name: "statuses_identity_id_fk"
    add_foreign_key "stocks", "companies", name: "stocks_company_id_fk"
    add_foreign_key "stocks", "identities", name: "stocks_identity_id_fk"
    add_foreign_key "stocks", "passwords", name: "stocks_password_id_fk"
    add_foreign_key "sun_exposures", "identities", name: "sun_exposures_identity_id_fk"
    add_foreign_key "temperatures", "identities", name: "temperatures_identity_id_fk"
    add_foreign_key "therapists", "contacts", name: "therapists_contact_id_fk"
    add_foreign_key "therapists", "identities", name: "therapists_identity_id_fk"
    add_foreign_key "to_dos", "identities", name: "to_dos_identity_id_fk"
    add_foreign_key "trip_pictures", "identity_files", name: "trip_pictures_identity_file_id_fk"
    add_foreign_key "trip_pictures", "identities", name: "trip_pictures_identity_id_fk"
    add_foreign_key "trip_pictures", "trips", name: "trip_pictures_trip_id_fk"
    add_foreign_key "trips", "identities", name: "trips_identity_id_fk"
    add_foreign_key "trips", "locations", name: "trips_location_id_fk"
    add_foreign_key "users", "identities", column: "primary_identity_id", name: "users_primary_identity_id_fk"
    add_foreign_key "vehicle_insurances", "companies", name: "vehicle_insurances_company_id_fk"
    add_foreign_key "vehicle_insurances", "identities", name: "vehicle_insurances_identity_id_fk"
    add_foreign_key "vehicle_insurances", "periodic_payments", name: "vehicle_insurances_periodic_payment_id_fk"
    add_foreign_key "vehicle_insurances", "vehicles", name: "vehicle_insurances_vehicle_id_fk"
    add_foreign_key "vehicle_loans", "identities", name: "vehicle_loans_identity_id_fk"
    add_foreign_key "vehicle_loans", "loans", name: "vehicle_loans_loan_id_fk"
    add_foreign_key "vehicle_loans", "vehicles", name: "vehicle_loans_vehicle_id_fk"
    add_foreign_key "vehicle_pictures", "identity_files", name: "vehicle_pictures_identity_file_id_fk"
    add_foreign_key "vehicle_pictures", "identities", name: "vehicle_pictures_identity_id_fk"
    add_foreign_key "vehicle_pictures", "vehicles", name: "vehicle_pictures_vehicle_id_fk"
    add_foreign_key "vehicle_services", "identities", name: "vehicle_services_identity_id_fk"
    add_foreign_key "vehicle_services", "vehicles", name: "vehicle_services_vehicle_id_fk"
    add_foreign_key "vehicle_warranties", "identities", name: "vehicle_warranties_identity_id_fk"
    add_foreign_key "vehicle_warranties", "vehicles", name: "vehicle_warranties_vehicle_id_fk"
    add_foreign_key "vehicle_warranties", "warranties", name: "vehicle_warranties_warranty_id_fk"
    add_foreign_key "vehicles", "identities", name: "vehicles_identity_id_fk"
    add_foreign_key "vehicles", "recreational_vehicles", name: "vehicles_recreational_vehicle_id_fk"
    add_foreign_key "vitamin_ingredients", "identities", name: "vitamin_ingredients_identity_id_fk"
    add_foreign_key "vitamin_ingredients", "vitamins", column: "parent_vitamin_id", name: "vitamin_ingredients_parent_vitamin_id_fk"
    add_foreign_key "vitamin_ingredients", "vitamins", name: "vitamin_ingredients_vitamin_id_fk"
    add_foreign_key "vitamins", "identities", name: "vitamins_identity_id_fk"
    add_foreign_key "warranties", "identities", name: "warranties_identity_id_fk"
    add_foreign_key "websites", "identities", name: "websites_identity_id_fk"
    add_foreign_key "weights", "identities", name: "weights_identity_id_fk"
    add_foreign_key "wisdoms", "identities", name: "wisdoms_identity_id_fk"
  end
end
