class UpdateMissingKeys < ActiveRecord::Migration[5.1]
  def change
    add_foreign_key "admin_emails", "emails", name: "admin_emails_email_id_fk"
    add_foreign_key "beaches", "locations", name: "beaches_location_id_fk"
    add_foreign_key "bet_contacts", "bets", name: "bet_contacts_bet_id_fk"
    add_foreign_key "blog_post_comments", "identities", name: "blog_post_comments_identity_id_fk"
    add_foreign_key "book_quotes", "identities", name: "book_quotes_identity_id_fk"
    add_foreign_key "cafes", "identities", name: "cafes_identity_id_fk"
    add_foreign_key "calendar_item_reminder_pendings", "identities", name: "calendar_item_reminder_pendings_identity_id_fk"
    add_foreign_key "charities", "identities", name: "charities_identity_id_fk"
    add_foreign_key "companies", "identities", column: "company_identity_id", name: "companies_company_identity_id_fk"
    add_foreign_key "computer_environment_addresses", "computer_environments", name: "computer_environment_addresses_computer_environment_id_fk"
    add_foreign_key "conversation_files", "identity_files", name: "conversation_files_identity_file_id_fk"
    add_foreign_key "credit_score_files", "credit_scores", name: "credit_score_files_credit_score_id_fk"
    add_foreign_key "dna_analyses", "imports", name: "dna_analyses_import_id_fk"
    add_foreign_key "drafts", "identities", name: "drafts_identity_id_fk"
    add_foreign_key "driver_license_files", "driver_licenses", name: "driver_license_files_driver_license_id_fk"
    add_foreign_key "education_files", "educations", name: "education_files_education_id_fk"
    add_foreign_key "favorite_product_links", "identities", name: "favorite_product_links_identity_id_fk"
    add_foreign_key "flight_legs", "companies", column: "flight_company_id", name: "flight_legs_flight_company_id_fk"
    add_foreign_key "flight_legs", "flights", name: "flight_legs_flight_id_fk"
    add_foreign_key "food_informations", "usda_foods", column: "usda_food_nutrient_databank_number", primary_key: "nutrient_databank_number", name: "food_informations_usda_food_nutrient_databank_number_fk"
    add_foreign_key "food_ingredients", "foods", name: "food_ingredients_food_id_fk"
    add_foreign_key "food_ingredients", "identities", name: "food_ingredients_identity_id_fk"
    add_foreign_key "food_ingredients", "foods", column: "parent_food_id", name: "food_ingredients_parent_food_id_fk"
    add_foreign_key "food_list_foods", "foods", name: "food_list_foods_food_id_fk"
    add_foreign_key "food_nutrient_informations", "usda_nutrients", column: "usda_nutrient_nutrient_number", primary_key: "nutrient_number", name: "food_nutrient_informations_usda_nutrient_nutrient_number_fk"
    add_foreign_key "food_nutrition_information_amounts", "food_nutrition_informations", name: "food_nutrition_information_amounts_food_nutrition_information_id_fk"
    add_foreign_key "foods", "identities", name: "foods_identity_id_fk"
    add_foreign_key "gas_stations", "identities", name: "gas_stations_identity_id_fk"
    add_foreign_key "gas_stations", "locations", name: "gas_stations_location_id_fk"
    add_foreign_key "genotype_calls", "dna_analyses", name: "genotype_calls_dna_analysis_id_fk"
    add_foreign_key "group_contacts", "contacts", name: "group_contacts_contact_id_fk"
    add_foreign_key "group_contacts", "groups", name: "group_contacts_group_id_fk"
    add_foreign_key "group_contacts", "identities", name: "group_contacts_identity_id_fk"
    add_foreign_key "groups", "identities", name: "groups_identity_id_fk"
    add_foreign_key "gun_files", "identity_files", name: "gun_files_identity_file_id_fk"
    add_foreign_key "gun_registration_files", "gun_registrations", name: "gun_registration_files_gun_registration_id_fk"
    add_foreign_key "gun_registration_files", "identity_files", name: "gun_registration_files_identity_file_id_fk"
    add_foreign_key "gun_registrations", "guns", name: "gun_registrations_gun_id_fk"
    add_foreign_key "gun_registrations", "identities", name: "gun_registrations_identity_id_fk"
    add_foreign_key "gun_registrations", "locations", name: "gun_registrations_location_id_fk"
    add_foreign_key "guns", "identities", name: "guns_identity_id_fk"
    add_foreign_key "headaches", "identities", name: "headaches_identity_id_fk"
    add_foreign_key "health_insurance_files", "identities", name: "health_insurance_files_identity_id_fk"
    add_foreign_key "health_insurances", "doctors", name: "health_insurances_doctor_id_fk"
    add_foreign_key "health_insurances", "companies", column: "group_company_id", name: "health_insurances_group_company_id_fk"
    add_foreign_key "health_insurances", "identities", name: "health_insurances_identity_id_fk"
    add_foreign_key "health_insurances", "companies", column: "insurance_company_id", name: "health_insurances_insurance_company_id_fk"
    add_foreign_key "health_insurances", "passwords", name: "health_insurances_password_id_fk"
    add_foreign_key "health_insurances", "periodic_payments", name: "health_insurances_periodic_payment_id_fk"
    add_foreign_key "heart_rates", "identities", name: "heart_rates_identity_id_fk"
    add_foreign_key "heights", "identities", name: "heights_identity_id_fk"
    add_foreign_key "hobbies", "identities", name: "hobbies_identity_id_fk"
    add_foreign_key "hypotheses", "identities", name: "hypotheses_identity_id_fk"
    add_foreign_key "hypotheses", "questions", name: "hypotheses_question_id_fk"
    add_foreign_key "hypothesis_experiments", "hypotheses", name: "hypothesis_experiments_hypothesis_id_fk"
    add_foreign_key "hypothesis_experiments", "identities", name: "hypothesis_experiments_identity_id_fk"
    add_foreign_key "ideas", "identities", name: "ideas_identity_id_fk"
    add_foreign_key "identities", "identities", name: "identities_identity_id_fk"
    add_foreign_key "identities", "users", name: "identities_user_id_fk"
    add_foreign_key "identity_drivers_licenses", "identity_files", name: "identity_drivers_licenses_identity_file_id_fk"
    add_foreign_key "identity_drivers_licenses", "identities", name: "identity_drivers_licenses_identity_id_fk"
    add_foreign_key "identity_drivers_licenses", "identities", column: "parent_identity_id", name: "identity_drivers_licenses_parent_identity_id_fk"
    add_foreign_key "identity_emails", "identities", name: "identity_emails_identity_id_fk"
    add_foreign_key "identity_emails", "identities", column: "parent_identity_id", name: "identity_emails_parent_identity_id_fk"
    add_foreign_key "identity_file_folders", "identities", name: "identity_file_folders_identity_id_fk"
    add_foreign_key "identity_file_folders", "identity_file_folders", column: "parent_folder_id", name: "identity_file_folders_parent_folder_id_fk"
    add_foreign_key "identity_files", "encrypted_values", column: "encrypted_password_id", name: "identity_files_encrypted_password_id_fk"
    add_foreign_key "identity_files", "identity_file_folders", column: "folder_id", name: "identity_files_folder_id_fk"
    add_foreign_key "identity_files", "identities", name: "identity_files_identity_id_fk"
    add_foreign_key "identity_locations", "identities", name: "identity_locations_identity_id_fk"
    add_foreign_key "identity_locations", "locations", name: "identity_locations_location_id_fk"
    add_foreign_key "identity_locations", "identities", column: "parent_identity_id", name: "identity_locations_parent_identity_id_fk"
    add_foreign_key "identity_phones", "identities", name: "identity_phones_identity_id_fk"
    add_foreign_key "identity_phones", "identities", column: "parent_identity_id", name: "identity_phones_parent_identity_id_fk"
    add_foreign_key "identity_pictures", "identity_files", name: "identity_pictures_identity_file_id_fk"
    add_foreign_key "identity_pictures", "identities", name: "identity_pictures_identity_id_fk"
    add_foreign_key "identity_pictures", "identities", column: "parent_identity_id", name: "identity_pictures_parent_identity_id_fk"
    add_foreign_key "identity_relationships", "contacts", name: "identity_relationships_contact_id_fk"
    add_foreign_key "identity_relationships", "identities", name: "identity_relationships_identity_id_fk"
    add_foreign_key "identity_relationships", "identities", column: "parent_identity_id", name: "identity_relationships_parent_identity_id_fk"
    add_foreign_key "import_files", "identity_files", name: "import_files_identity_file_id_fk"
    add_foreign_key "injury_files", "identity_files", name: "injury_files_identity_file_id_fk"
    add_foreign_key "insurance_card_files", "insurance_cards", name: "insurance_card_files_insurance_card_id_fk"
    add_foreign_key "invites", "users", name: "invites_user_id_fk"
    add_foreign_key "item_files", "items", name: "item_files_item_id_fk"
    add_foreign_key "job_awards", "jobs", name: "job_awards_job_id_fk"
    add_foreign_key "job_reviews", "identities", name: "job_reviews_identity_id_fk"
    add_foreign_key "job_salaries", "identities", name: "job_salaries_identity_id_fk"
    add_foreign_key "job_salaries", "jobs", name: "job_salaries_job_id_fk"
    add_foreign_key "jobs", "companies", name: "jobs_company_id_fk"
    add_foreign_key "jobs", "identities", name: "jobs_identity_id_fk"
    add_foreign_key "jobs", "locations", column: "internal_address_id", name: "jobs_internal_address_id_fk"
    add_foreign_key "jobs", "contacts", column: "manager_contact_id", name: "jobs_manager_contact_id_fk"
    add_foreign_key "jokes", "identities", name: "jokes_identity_id_fk"
    add_foreign_key "life_goals", "identities", name: "life_goals_identity_id_fk"
    add_foreign_key "life_insurances", "companies", name: "life_insurances_company_id_fk"
    add_foreign_key "life_insurances", "identities", name: "life_insurances_identity_id_fk"
    add_foreign_key "life_insurances", "periodic_payments", name: "life_insurances_periodic_payment_id_fk"
    add_foreign_key "list_items", "identities", name: "list_items_identity_id_fk"
    add_foreign_key "list_items", "lists", name: "list_items_list_id_fk"
    add_foreign_key "lists", "identities", name: "lists_identity_id_fk"
    add_foreign_key "loans", "identities", name: "loans_identity_id_fk"
    add_foreign_key "location_phones", "identities", name: "location_phones_identity_id_fk"
    add_foreign_key "location_phones", "locations", name: "location_phones_location_id_fk"
    add_foreign_key "locations", "identities", name: "locations_identity_id_fk"
    add_foreign_key "meal_drinks", "drinks", name: "meal_drinks_drink_id_fk"
    add_foreign_key "meal_drinks", "identities", name: "meal_drinks_identity_id_fk"
    add_foreign_key "meal_drinks", "meals", name: "meal_drinks_meal_id_fk"
    add_foreign_key "meal_foods", "foods", name: "meal_foods_food_id_fk"
    add_foreign_key "meal_foods", "identities", name: "meal_foods_identity_id_fk"
    add_foreign_key "meal_foods", "meals", name: "meal_foods_meal_id_fk"
    add_foreign_key "meal_vitamins", "identities", name: "meal_vitamins_identity_id_fk"
    add_foreign_key "meal_vitamins", "meals", name: "meal_vitamins_meal_id_fk"
    add_foreign_key "meal_vitamins", "vitamins", name: "meal_vitamins_vitamin_id_fk"
    add_foreign_key "meals", "identities", name: "meals_identity_id_fk"
    add_foreign_key "meals", "locations", name: "meals_location_id_fk"
    add_foreign_key "media_dumps", "identities", name: "media_dumps_identity_id_fk"
    add_foreign_key "medical_condition_instances", "identities", name: "medical_condition_instances_identity_id_fk"
    add_foreign_key "medical_condition_instances", "medical_conditions", name: "medical_condition_instances_medical_condition_id_fk"
    add_foreign_key "medical_conditions", "identities", name: "medical_conditions_identity_id_fk"
    add_foreign_key "medicine_usage_medicines", "identities", name: "medicine_usage_medicines_identity_id_fk"
    add_foreign_key "medicine_usage_medicines", "medicines", name: "medicine_usage_medicines_medicine_id_fk"
    add_foreign_key "medicine_usage_medicines", "medicine_usages", name: "medicine_usage_medicines_medicine_usage_id_fk"
    add_foreign_key "medicine_usages", "identities", name: "medicine_usages_identity_id_fk"
    add_foreign_key "medicines", "identities", name: "medicines_identity_id_fk"
    add_foreign_key "membership_files", "identity_files", name: "membership_files_identity_file_id_fk"
    add_foreign_key "memberships", "identities", name: "memberships_identity_id_fk"
    add_foreign_key "memberships", "periodic_payments", name: "memberships_periodic_payment_id_fk"
    add_foreign_key "message_contacts", "contacts", name: "message_contacts_contact_id_fk"
    add_foreign_key "movie_theaters", "identities", name: "movie_theaters_identity_id_fk"
    add_foreign_key "movie_theaters", "locations", name: "movie_theaters_location_id_fk"
    add_foreign_key "movies", "identities", name: "movies_identity_id_fk"
    add_foreign_key "movies", "contacts", column: "lent_to_id", name: "movies_lent_to_id_fk"
    add_foreign_key "movies", "contacts", column: "recommender_id", name: "movies_recommender_id_fk"
    add_foreign_key "museums", "identities", name: "museums_identity_id_fk"
    add_foreign_key "museums", "locations", name: "museums_location_id_fk"
    add_foreign_key "museums", "websites", name: "museums_website_id_fk"
    add_foreign_key "music_album_files", "music_albums", name: "music_album_files_music_album_id_fk"
    add_foreign_key "music_albums", "identities", name: "music_albums_identity_id_fk"
    add_foreign_key "musical_groups", "identities", name: "musical_groups_identity_id_fk"
    add_foreign_key "myplaceonline_quick_category_displays", "identities", name: "myplaceonline_quick_category_displays_identity_id_fk"
    add_foreign_key "myplaceonline_searches", "identities", name: "myplaceonline_searches_identity_id_fk"
    add_foreign_key "myplets", "identities", name: "myplets_identity_id_fk"
    add_foreign_key "notepads", "identities", name: "notepads_identity_id_fk"
    add_foreign_key "paid_taxes", "identities", name: "paid_taxes_identity_id_fk"
    add_foreign_key "pains", "identities", name: "pains_identity_id_fk"
    add_foreign_key "passport_pictures", "identity_files", name: "passport_pictures_identity_file_id_fk"
    add_foreign_key "passport_pictures", "identities", name: "passport_pictures_identity_id_fk"
    add_foreign_key "passport_pictures", "passports", name: "passport_pictures_passport_id_fk"
    add_foreign_key "passports", "identities", name: "passports_identity_id_fk"
    add_foreign_key "password_secrets", "encrypted_values", column: "answer_encrypted_id", name: "password_secrets_answer_encrypted_id_fk"
    add_foreign_key "password_secrets", "identities", name: "password_secrets_identity_id_fk"
    add_foreign_key "password_secrets", "passwords", name: "password_secrets_password_id_fk"
    add_foreign_key "passwords", "identities", name: "passwords_identity_id_fk"
    add_foreign_key "passwords", "encrypted_values", column: "password_encrypted_id", name: "passwords_password_encrypted_id_fk"
    add_foreign_key "periodic_payments", "identities", name: "periodic_payments_identity_id_fk"
    add_foreign_key "phones", "identities", name: "phones_identity_id_fk"
    add_foreign_key "phones", "companies", column: "manufacturer_id", name: "phones_manufacturer_id_fk"
    add_foreign_key "phones", "passwords", name: "phones_password_id_fk"
    add_foreign_key "playlist_songs", "identities", name: "playlist_songs_identity_id_fk"
    add_foreign_key "playlist_songs", "playlists", name: "playlist_songs_playlist_id_fk"
    add_foreign_key "playlist_songs", "songs", name: "playlist_songs_song_id_fk"
    add_foreign_key "playlists", "identities", name: "playlists_identity_id_fk"
    add_foreign_key "poems", "identities", name: "poems_identity_id_fk"
    add_foreign_key "point_displays", "identities", name: "point_displays_identity_id_fk"
    add_foreign_key "prescriptions", "doctors", name: "prescriptions_doctor_id_fk"
    add_foreign_key "promises", "identities", name: "promises_identity_id_fk"
    add_foreign_key "promotions", "identities", name: "promotions_identity_id_fk"
    add_foreign_key "questions", "identities", name: "questions_identity_id_fk"
    add_foreign_key "recipes", "identities", name: "recipes_identity_id_fk"
    add_foreign_key "recreational_vehicle_insurances", "companies", name: "recreational_vehicle_insurances_company_id_fk"
    add_foreign_key "recreational_vehicle_insurances", "identities", name: "recreational_vehicle_insurances_identity_id_fk"
    add_foreign_key "recreational_vehicle_insurances", "periodic_payments", name: "recreational_vehicle_insurances_periodic_payment_id_fk"
    add_foreign_key "recreational_vehicle_insurances", "recreational_vehicles", name: "recreational_vehicle_insurances_recreational_vehicle_id_fk"
    add_foreign_key "recreational_vehicle_loans", "identities", name: "recreational_vehicle_loans_identity_id_fk"
    add_foreign_key "recreational_vehicle_loans", "loans", name: "recreational_vehicle_loans_loan_id_fk"
    add_foreign_key "recreational_vehicle_loans", "recreational_vehicles", name: "recreational_vehicle_loans_recreational_vehicle_id_fk"
    add_foreign_key "recreational_vehicle_measurements", "identities", name: "recreational_vehicle_measurements_identity_id_fk"
    add_foreign_key "recreational_vehicle_measurements", "recreational_vehicles", name: "recreational_vehicle_measurements_recreational_vehicle_id_fk"
    add_foreign_key "recreational_vehicle_pictures", "identity_files", name: "recreational_vehicle_pictures_identity_file_id_fk"
    add_foreign_key "recreational_vehicle_pictures", "identities", name: "recreational_vehicle_pictures_identity_id_fk"
    add_foreign_key "recreational_vehicle_pictures", "recreational_vehicles", name: "recreational_vehicle_pictures_recreational_vehicle_id_fk"
    add_foreign_key "recreational_vehicle_service_files", "identities", name: "recreational_vehicle_service_files_identity_id_fk"
    add_foreign_key "recreational_vehicles", "identities", name: "recreational_vehicles_identity_id_fk"
    add_foreign_key "recreational_vehicles", "locations", column: "location_purchased_id", name: "recreational_vehicles_location_purchased_id_fk"
    add_foreign_key "regimens", "identities", name: "regimens_identity_id_fk"
    add_foreign_key "reminders", "calendar_items", name: "reminders_calendar_item_id_fk"
    add_foreign_key "repeats", "identities", name: "repeats_identity_id_fk"
    add_foreign_key "reputation_report_files", "identity_files", name: "reputation_report_files_identity_file_id_fk"
    add_foreign_key "reputation_reports", "agents", name: "reputation_reports_agent_id_fk"
    add_foreign_key "restaurants", "identities", name: "restaurants_identity_id_fk"
    add_foreign_key "restaurants", "locations", name: "restaurants_location_id_fk"
    add_foreign_key "retirement_plan_amount_files", "identities", name: "retirement_plan_amount_files_identity_id_fk"
    add_foreign_key "reward_program_files", "reward_programs", name: "reward_program_files_reward_program_id_fk"
    add_foreign_key "reward_programs", "identities", name: "reward_programs_identity_id_fk"
    add_foreign_key "reward_programs", "passwords", name: "reward_programs_password_id_fk"
    add_foreign_key "shares", "identities", name: "shares_identity_id_fk"
    add_foreign_key "shopping_list_items", "identities", name: "shopping_list_items_identity_id_fk"
    add_foreign_key "shopping_list_items", "shopping_lists", name: "shopping_list_items_shopping_list_id_fk"
    add_foreign_key "shopping_lists", "identities", name: "shopping_lists_identity_id_fk"
    add_foreign_key "skin_treatments", "identities", name: "skin_treatments_identity_id_fk"
    add_foreign_key "sleep_measurements", "identities", name: "sleep_measurements_identity_id_fk"
    add_foreign_key "snoozed_due_items", "calendars", name: "snoozed_due_items_calendar_id_fk"
    add_foreign_key "snoozed_due_items", "identities", name: "snoozed_due_items_identity_id_fk"
    add_foreign_key "songs", "identity_files", name: "songs_identity_file_id_fk"
    add_foreign_key "songs", "identities", name: "songs_identity_id_fk"
    add_foreign_key "songs", "musical_groups", name: "songs_musical_group_id_fk"
    add_foreign_key "ssh_keys", "encrypted_values", column: "ssh_private_key_encrypted_id", name: "ssh_keys_ssh_private_key_encrypted_id_fk"
    add_foreign_key "statuses", "identities", name: "statuses_identity_id_fk"
    add_foreign_key "stock_files", "identities", name: "stock_files_identity_id_fk"
    add_foreign_key "stocks", "companies", name: "stocks_company_id_fk"
    add_foreign_key "stocks", "identities", name: "stocks_identity_id_fk"
    add_foreign_key "stocks", "passwords", name: "stocks_password_id_fk"
    add_foreign_key "sun_exposures", "identities", name: "sun_exposures_identity_id_fk"
    add_foreign_key "surgery_files", "identity_files", name: "surgery_files_identity_file_id_fk"
    add_foreign_key "temperatures", "identities", name: "temperatures_identity_id_fk"
    add_foreign_key "test_object_files", "identity_files", name: "test_object_files_identity_file_id_fk"
    add_foreign_key "test_score_files", "identity_files", name: "test_score_files_identity_file_id_fk"
    add_foreign_key "text_message_contacts", "identities", name: "text_message_contacts_identity_id_fk"
    add_foreign_key "text_message_contacts", "text_messages", name: "text_message_contacts_text_message_id_fk"
    add_foreign_key "text_message_groups", "groups", name: "text_message_groups_group_id_fk"
    add_foreign_key "therapists", "contacts", name: "therapists_contact_id_fk"
    add_foreign_key "therapists", "identities", name: "therapists_identity_id_fk"
    add_foreign_key "timings", "identities", name: "timings_identity_id_fk"
    add_foreign_key "to_dos", "identities", name: "to_dos_identity_id_fk"
    add_foreign_key "trip_pictures", "identity_files", name: "trip_pictures_identity_file_id_fk"
    add_foreign_key "trip_pictures", "identities", name: "trip_pictures_identity_id_fk"
    add_foreign_key "trip_pictures", "trips", name: "trip_pictures_trip_id_fk"
    add_foreign_key "trips", "identities", name: "trips_identity_id_fk"
    add_foreign_key "trips", "locations", name: "trips_location_id_fk"
    #add_foreign_key "usda_foods", "usda_food_groups", column: "food_group_code", primary_key: "code", name: "usda_foods_food_group_code_fk"
    #add_foreign_key "usda_foods_nutrients", "usda_foods", column: "nutrient_databank_number", primary_key: "nutrient_databank_number", name: "usda_foods_nutrients_nutrient_databank_number_fk", on_update: :nullify, on_delete: :nullify
    #add_foreign_key "usda_foods_nutrients", "usda_nutrients", column: "nutrient_number", primary_key: "nutrient_number", name: "usda_foods_nutrients_nutrient_number_fk", on_update: :nullify, on_delete: :nullify
    #add_foreign_key "usda_footnotes", "usda_foods", column: "nutrient_databank_number", primary_key: "nutrient_databank_number", name: "usda_footnotes_nutrient_databank_number_fk"
    #add_foreign_key "usda_footnotes", "usda_nutrients", column: "nutrient_number", primary_key: "nutrient_number", name: "usda_footnotes_nutrient_number_fk"
    #add_foreign_key "usda_weights", "usda_foods", column: "nutrient_databank_number", primary_key: "nutrient_databank_number", name: "usda_weights_nutrient_databank_number_fk"
    add_foreign_key "vaccine_files", "identity_files", name: "vaccine_files_identity_file_id_fk"
    add_foreign_key "vehicle_insurances", "companies", name: "vehicle_insurances_company_id_fk"
    add_foreign_key "vehicle_insurances", "identities", name: "vehicle_insurances_identity_id_fk"
    add_foreign_key "vehicle_insurances", "periodic_payments", name: "vehicle_insurances_periodic_payment_id_fk"
    add_foreign_key "vehicle_insurances", "vehicles", name: "vehicle_insurances_vehicle_id_fk"
    add_foreign_key "vehicle_loans", "identities", name: "vehicle_loans_identity_id_fk"
    add_foreign_key "vehicle_loans", "loans", name: "vehicle_loans_loan_id_fk"
    add_foreign_key "vehicle_loans", "vehicles", name: "vehicle_loans_vehicle_id_fk"
    add_foreign_key "vehicle_pictures", "identity_files", name: "vehicle_pictures_identity_file_id_fk"
    add_foreign_key "vehicle_pictures", "identities", name: "vehicle_pictures_identity_id_fk"
    add_foreign_key "vehicle_pictures", "vehicles", name: "vehicle_pictures_vehicle_id_fk"
    add_foreign_key "vehicle_services", "identities", name: "vehicle_services_identity_id_fk"
    add_foreign_key "vehicle_services", "vehicles", name: "vehicle_services_vehicle_id_fk"
    add_foreign_key "vehicle_warranties", "identities", name: "vehicle_warranties_identity_id_fk"
    add_foreign_key "vehicle_warranties", "vehicles", name: "vehicle_warranties_vehicle_id_fk"
    add_foreign_key "vehicle_warranties", "warranties", name: "vehicle_warranties_warranty_id_fk"
    add_foreign_key "vehicles", "identities", name: "vehicles_identity_id_fk"
    add_foreign_key "vehicles", "recreational_vehicles", name: "vehicles_recreational_vehicle_id_fk"
    add_foreign_key "vitamin_ingredients", "identities", name: "vitamin_ingredients_identity_id_fk"
    add_foreign_key "vitamin_ingredients", "vitamins", column: "parent_vitamin_id", name: "vitamin_ingredients_parent_vitamin_id_fk"
    add_foreign_key "vitamin_ingredients", "vitamins", name: "vitamin_ingredients_vitamin_id_fk"
    add_foreign_key "vitamins", "identities", name: "vitamins_identity_id_fk"
    add_foreign_key "warranties", "identities", name: "warranties_identity_id_fk"
    add_foreign_key "web_comics", "identities", name: "web_comics_identity_id_fk"
    add_foreign_key "website_domain_myplets", "categories", name: "website_domain_myplets_category_id_fk"
    add_foreign_key "website_domain_myplets", "website_domains", name: "website_domain_myplets_website_domain_id_fk"
    add_foreign_key "website_domain_properties", "website_domains", name: "website_domain_properties_website_domain_id_fk"
    add_foreign_key "website_domain_registrations", "repeats", name: "website_domain_registrations_repeat_id_fk"
    add_foreign_key "website_passwords", "passwords", name: "website_passwords_password_id_fk"
    add_foreign_key "websites", "identities", name: "websites_identity_id_fk"
    add_foreign_key "weights", "identities", name: "weights_identity_id_fk"
    add_foreign_key "wisdom_files", "identity_files", name: "wisdom_files_identity_file_id_fk"
    add_foreign_key "wisdoms", "identities", name: "wisdoms_identity_id_fk"
  end
end
